# Tugas Pre-Processing Data

In [14]:
import pandas as pd
import numpy as np

In [15]:
data1=pd.read_csv("CRAFT.csv",sep=";")

In [16]:
data1.describe()
np.sum(data1.isnull())

GameID                   0
LeagueIndex              0
Age                     55
HoursPerWeek            56
TotalHours              57
APM                      0
SelectByHotkeys          0
AssignToHotkeys          0
UniqueHotkeys            0
MinimapAttacks           0
MinimapRightClicks       0
NumberOfPACs             0
GapBetweenPACs           0
ActionLatency            0
ActionsInPAC             0
TotalMapExplored         0
WorkersMade              0
UniqueUnitsMade          0
ComplexUnitsMade         0
ComplexAbilitiesUsed     0
dtype: int64

In [17]:
data1['Age']=data1['Age'].fillna((data1['Age'].mean()))
data1['HoursPerWeek']=data1['HoursPerWeek'].fillna((data1['HoursPerWeek'].mean()))
data1['TotalHours']=data1['TotalHours'].fillna((data1['TotalHours'].mean()))
np.sum(data1.isnull())

GameID                  0
LeagueIndex             0
Age                     0
HoursPerWeek            0
TotalHours              0
APM                     0
SelectByHotkeys         0
AssignToHotkeys         0
UniqueHotkeys           0
MinimapAttacks          0
MinimapRightClicks      0
NumberOfPACs            0
GapBetweenPACs          0
ActionLatency           0
ActionsInPAC            0
TotalMapExplored        0
WorkersMade             0
UniqueUnitsMade         0
ComplexUnitsMade        0
ComplexAbilitiesUsed    0
dtype: int64

In [19]:
from scipy import stats
z=np.abs(stats.zscore(data1._get_numeric_data()))
print(z)
data1=data1[(z<3).all(axis=1)]
print(data1.shape)

[[1.74772386 0.53780497 1.28301317 ... 0.28750617 0.53507146 0.5349699 ]
 [1.74662074 0.53780497 0.32412662 ... 0.82588645 0.53507146 0.24769891]
 [1.74625303 0.12134589 2.00217808 ... 0.28750617 0.53507146 0.17677344]
 ...
 [1.9440712  2.51525755 0.         ... 1.36426673 0.53507146 0.5349699 ]
 [1.94480661 2.51525755 0.         ... 0.28750617 0.53507146 1.84584096]
 [1.94517432 2.51525755 0.         ... 0.25087411 3.57810587 2.84007958]]
(2781, 20)
